version: '3.8'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:      
      - '80:80' 
      - '443:443' 
      - '81:81'      
    environment:     
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "admin"
      DB_MYSQL_PASSWORD: "CHNAGEME"
      DB_MYSQL_NAME: "nginx"    
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    depends_on:
      - db

  db:
    image: 'jc21/mariadb-aria:latest'
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 'CHNAGEME'
      MYSQL_DATABASE: 'nginx'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'CHNAGEME'
      MARIADB_AUTO_UPGRADE: '1'
    volumes:
      - ./mysql:/var/lib/mysql