version: '3.8'
 
 services:
   open-webui:
     image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
     ports:
       - "8282:8080"
     extra_hosts:
       - "host.docker.internal:host-gateway"
     volumes:
       - open-webui:/app/backend/data
	 environment:
      - OLLAMA_BASE_URL=http://localhost:11434
     restart: unless-stopped
	 
 
 volumes:
   open-webui: