version: '3'
services:
  obsidian:
    image: lscr.io/linuxserver/obsidian:latest
    container_name: obsidian
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - /home/user/obsidian/config:/config
    ports:
      - 3004:3000
      - 3005:3001
    devices:
      - /dev/dri:/dev/dri #optional
    shm_size: "1gb"